version: 2
updates:
  # Enable version updates for Python Pip
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      python-packages:
        patterns:
          - "*"
  # Enable version updates for Github Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
